package com.cts.java8.fi;

import java.security.SecureRandom;
import java.util.function.Supplier;

public class SupplierFI {
	
	public static void main(String[] args) {
		
		//	Program to generate 6 digit OTP
		
		Supplier<Integer> otpGenerator = () -> {
			return new SecureRandom().nextInt(100000, 999999);
		};
		
		System.out.println("OTP generated by system: " + otpGenerator.get());
	}

}
